language: go
go:
- 1.11
script:
- "./make_official.sh"
- "./spiro --help || true"
- "./spiro -version"
- "./run_demos.sh"
before_deploy:
- cd build && sha256sum spiro-* > SHA256SUMS && cd ..
- find build
deploy:
  provider: releases
  api_key:
    secure: upEmtnnuVemZuXkjiyclscNm9RD+2F3Pffrdmvg32/FqFvCAeS9ioWOu+dqknGvo7yITsHTvyoX547OD8lzkcc+G6BWBXG0wEM8wzaZmrNZ9BqjuPpJ73dhzS016FMyKwJiLy2haKAIu75z5Jcnby/e28VpHQtT6aDKWvUnoa0dyq6kwX93JJLY1iVL3Nuo8PQR1zLdTwknMFoIkxCsUZD0y0xN4u7vmQqyoVameT/CppeArjRdzDDaBWhdZzGqUlxZxrs1f0ALA0LYKyGJjU0J65j0BRDnYrydIjrJgy+PyinPgcC97ifyBldIvqqkR47dJwuwuf+Olh709Il2l8AjJtluMBC8M9CPvMbUg4gSUG2SaIeue9vVo6JzFL/+gJrN1SFPIttRV3Ftbt9UxX8r+40SOLafyBKucoi+jlP4G/wPCeQdb+joybtKHLb6OWkpD/FaH1De8kpELCTNsZCKJAyUgRGk5uVrCVjlEbkZtu5TilBAK+0dsXySSE5QfqyrbZxOhJ+MzMSpMsQ5A8JR/8gIl8GKi2gmeXIPYfcxpmJkCrMqykccMdbB+TFzaXDbidJWgPxXR4nN7QYCVVzf7KUpsZguQ0UByzmhds8/A6MMM5Ml/KVBD35nBKtnhCQRgqd7ng9XAPnEgPCOIuSlE6Ebq9PEJ/n9HE6VWDmo=
  skip_cleanup: true
  file:
    - build/spiro-linux-amd64
    - build/spiro-darwin-amd64
    - build/spiro-windows-amd64
    - build/SHA256SUMS
  on:
    repo: astromechza/spiro
    tags: true
    all_branches: false
